### ISSUE TITLE
直接cmake下  修改下路径 就可以使用吗？ 

### ISSUE THREAD

**Issue by weiyaokun** [chuzhixing/yolov5_obb_onnxruntime_deploy#1]

**Comment by chuzhixing** [comment]
sorry，之前没看到这个issue消息。下载下来，修改下opencv onnxruntime的路径，应该就能用了。
你也可以建立一个配置好了opencv onnxruntime的visual studio工程，把那4个源码文件拷过去就能正常使用了。

**Comment by DWendou** [comment]
> sorry，之前没看到这个issue消息。下载下来，修改下opencv onnxruntime的路径，应该就能用了。 你也可以建立一个配置好了opencv onnxruntime的visual studio工程，把那4个源码文件拷过去就能正常使用了。

是不是需要自己配置CMakeLists.txt文件？

**Comment by chuzhixing** [comment]
> > sorry，之前没看到这个issue消息。下载下来，修改下opencv onnxruntime的路径，应该就能用了。 你也可以建立一个配置好了opencv onnxruntime的visual studio工程，把那4个源码文件拷过去就能正常使用了。
> 
> 是不是需要自己配置CMakeLists.txt文件？


可以通过这样的步骤，使用本仓库的代码。
0 把代码下载下来。
1 在本地创建一个visual studio工程。
2 工程中配置opencv onnxruntime，引入这两个第三方库。
3 把那本仓库5个源码文件拷过去，并引入到工程中。
4 修改下main.cpp中模型路径、输入、输出图片地址。
5 编译运行。

**Comment by DWendou** [comment]
> > > sorry，之前没看到这个issue消息。下载下来，修改下opencv onnxruntime的路径，应该就能用了。 你也可以建立一个配置好了opencv onnxruntime的visual studio工程，把那4个源码文件拷过去就能正常使用了。
> > 
> > 
> > 是不是需要自己配置CMakeLists.txt文件？
> 
> 可以通过这样的步骤，使用本仓库的代码。 0 把代码下载下来。 1 在本地创建一个visual studio工程。 2 工程中配置opencv onnxruntime，引入这两个第三方库。 3 把那本仓库5个源码文件拷过去，并引入到工程中。 4 修改下main.cpp中模型路径、输入、输出图片地址。 5 编译运行。

非常感谢您的回复

**Comment by DWendou** [comment]
> > > sorry，之前没看到这个issue消息。下载下来，修改下opencv onnxruntime的路径，应该就能用了。 你也可以建立一个配置好了opencv onnxruntime的visual studio工程，把那4个源码文件拷过去就能正常使用了。
> > 
> > 
> > 是不是需要自己配置CMakeLists.txt文件？
> 
> 可以通过这样的步骤，使用本仓库的代码。 0 把代码下载下来。 1 在本地创建一个visual studio工程。 2 工程中配置opencv onnxruntime，引入这两个第三方库。 3 把那本仓库5个源码文件拷过去，并引入到工程中。 4 修改下main.cpp中模型路径、输入、输出图片地址。 5 编译运行。

你这个是Windows平台的编译方式，你的代码里面好像有一些代码在Linux系统中编译通不过，我平替了一下，才在Linux平台上编译通过的，需要写一下Cmakelist.txt。
